variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - /root/.m2/repository/

.validate: &validate
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS test-compile'

# For merge requests do not `deploy` but only run `verify`.
.verify: &verify
  stage: test
  script:
    - 'nohup mvn exec:java -Dexec.mainClass="org.hsqldb.server.Server" -Dexec.args="-database.0 file:target/data/databases/estagiarios --dbname.0 estagiarios" &'
    - 'mvn $MAVEN_CLI_OPTS test-compile'
    - 'mvn $MAVEN_CLI_OPTS verify -P integration'
  except:
    - master

# Validate merge requests using JDK8
validate:jdk8:
  <<: *validate
  image: maven:3.3.9-jdk-8


# Verify merge requests using JDK8
verify:jdk8:
  <<: *verify
  image: maven:3.3.9-jdk-8
